name: 'dotnet-release'
description: 'Checks for new official releases of the .NET SDK.'
author: 'Martin Costello'
branding:
  icon: 'refresh-cw'
  color: 'purple'
inputs:
  github-token:
    description: 'The GitHub token to use query for releases and to dispatch events.'
    default: ${{ github.token }}
    required: false
  state-token:
    description: 'The GitHub token to use to update the state.'
    default: ${{ github.token }}
    required: false
  ref:
    description: 'The dotnet/core ref to check for a new release against.'
    required: false
    type: string
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
