name: 'dotnet-release'
description: 'Checks for new official releases of the .NET SDK.'
author: 'Martin Costello'
branding:
  icon: 'refresh-cw'
  color: 'purple'
inputs:
  github-token:
    description: 'The GitHub token to use query for releases and to dispatch events.'
    required: false
    default: ${{ github.token }}
  state-token:
    description: 'The GitHub token to use to update the state.'
    required: false
    default: ${{ github.token }}
  ref:
    description: 'The dotnet/core ref to check for a new release against.'
    required: false
    default: ''
outputs:
  sdk-versions:
    description: 'A JSON array of the .NET SDK versions that were released.'
runs:
  using: 'node20'
  main: 'dist/main.js'
