name: 'dotnet-version-report'
description: 'Generates a report of the .NET SDK versions used by the default branch of repositories.'
author: 'Martin Costello'
branding:
  icon: 'file-text'
  color: 'purple'
inputs:
  github-token:
    description: 'The GitHub token to use.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/main.js'
