name: 'get-github-token'
description: 'Gets a GitHub token from a broker.'
author: 'Martin Costello'
branding:
  icon: 'lock'
  color: 'green'
inputs:
  profile-name:
    description: 'The name of the profile to get a GitHub token for.'
    required: true
outputs:
  token:
    description: 'A GitHub token for the specified profile.'
  token-type:
    description: 'The type of the GitHub token.'
  app-id:
    description: 'If the token type is "app", the ID of the GitHub App.'
  app-slug:
    description: 'If the token type is "app", the slug of the GitHub App.'
  installation-id:
    description: 'If the token type is "app", the installation ID of the GitHub App.'
runs:
  using: 'node24'
  main: 'dist/main.js'
  post: 'dist/post.js'
