name: 'get-dotnet-repos'
description: 'Gets the .NET repositories that the specified GitHub token has write access to.'
author: 'Martin Costello'
branding:
  icon: 'refresh-cw'
  color: 'blue'
inputs:
  branch:
    description: 'The branch to check for the presence of .NET in.'
    required: false
    default: ''
  github-token:
    description: 'The GitHub token to use.'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'An optional single repository to check.'
    required: false
    default: ''
outputs:
  repositories:
    description: 'A JSON array of the repositories for which .NET is present that can be pushed to by github-token.'
runs:
  using: 'node20'
  main: 'dist/main.js'
