name: 'is-dotnet-change-available'
description: 'Determines whether the changes from a pull request are available in a .NET installer build'
author: 'Martin Costello'
branding:
  icon: 'help-circle'
  color: 'purple'
inputs:
  github-token:
    description: 'The GitHub token to use.'
    required: false
    default: ${{ github.token }}
  channel:
    description: 'The channel to use as the default for searching for a .NET SDK release.'
    required: false
    default: ''
  pull-request:
    description: 'The number of the pull request to search for.'
    required: true
    default: ''
  repository-name:
    description: 'The name of the dotnet repository containing the pull request.'
    required: true
    default: ''
outputs:
  is-available:
    description: 'Whether the changes from the pull request are available in an artifact from the dotnet/installer repository.'
  installer-version:
    description: 'If the changes are available, the latest version of the .NET SDK that contains the changes.'
runs:
  using: 'node20'
  main: 'dist/main.js'
