name: dotnet-upgrade-report-for-nightly

on:
  schedule:
    - cron: '00 07 * * *'
    - cron: '45 10 * * *'
    - cron: '30 13 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  update-from-nightly:
    uses: ./.github/workflows/dotnet-upgrade-report.yml
    secrets: inherit
    with:
      branch: 'dotnet-nightly'
      gist-id: ${{ vars.NIGHTLY_UPGRADE_REPORT_GIST_ID }}
