name: dotnet-version-report

on:
  schedule:
    - cron: '30 07 * * MON'
  workflow_dispatch:

permissions: {}

jobs:
  generate:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false

    environment:
      name: admin
      deployment: false

    permissions:
      contents: read
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Get GitHub token
        id: get-github-token
        uses: ./actions/get-github-token
        with:
          profile-name: read

      - name: Generate report
        uses: ./actions/dotnet-version-report
        with:
          github-token: ${{ steps.get-github-token.outputs.token }}
