name: dotnet-release

on:
  schedule:
    - cron: '0 08-22 * * MON,WED-FRI'
    - cron: '*/10 08-22 * * TUE'
  workflow_dispatch:
    inputs:
      ref:
        description: 'The dotnet/core ref to check for a new release against.'
        required: false
        type: string
        default: ''

permissions: {}

jobs:
  check-for-release:
    timeout-minutes: 10

    environment:
      name: admin
      deployment: false

    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-slim

    steps:

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Get GitHub token
        id: get-github-token
        uses: ./actions/get-github-token
        with:
          profile-name: admin

      - name: Check for new .NET releases
        uses: ./actions/dotnet-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state-token: ${{ steps.get-github-token.outputs.token }}
          ref: ${{ inputs.ref || vars.DOTNET_CORE_SHA }}
