name: dotnet-upgrade-report

on:
  schedule:
    - cron: '30 07 * * *'
    - cron: '00 13 * * *'
  workflow_call:
    inputs:
      branch:
        description: 'The branch to run the report for.'
        required: true
        type: string
      gist-id:
        description: 'The optional ID of the Gist to write the report to.'
        required: false
        type: string
        default: ''
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the report for.'
        required: false
        type: choice
        options:
          - 'dotnet-vnext'
          - 'dotnet-nightly'
        default: 'dotnet-vnext'
      gist-id:
        description: 'The optional ID of the Gist to write the report to.'
        required: false
        type: string
        default: ''

permissions: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}-${{ inputs.branch }}'
      cancel-in-progress: false

    steps:

      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Generate report
        uses: ./actions/dotnet-upgrade-report
        with:
          branch: ${{ inputs.branch }}
          channel: ${{ vars.DOTNET_NIGHTLY_CHANNEL }}
          gist-id: ${{ inputs.gist-id || ((inputs.branch == 'dotnet-vnext' || github.event_name == 'schedule') && vars.UPGRADE_REPORT_GIST_ID) || '' }}
          github-token: ${{ secrets.ACCESS_TOKEN }}
