name: dotnet-upgrade-report

on:
  schedule:
    - cron: '30 08 * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the report for.'
        required: false
        type: choice
        options:
          - 'dotnet-vnext'
          - 'dotnet-nightly'
        default: 'dotnet-vnext'

permissions: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}-${{ inputs.branch }}'
      cancel-in-progress: false

    steps:

      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Generate report
        uses: ./actions/dotnet-upgrade-report
        with:
          branch: ${{ inputs.branch }}
          channel: ${{ vars.DOTNET_NIGHTLY_CHANNEL }}
          gist-id: ${{ vars.UPGRADE_REPORT_GIST_ID }}
          github-token: ${{ secrets.ACCESS_TOKEN }}
