name: dotnet-dependencies-updated
run-name: ${{ github.event.client_payload.repository }}

on:
  repository_dispatch:
    types: [ dotnet_dependencies_updated ]

permissions: {}

jobs:
  rebase:
    if: github.event.client_payload.ref_name == 'main' || github.event.client_payload.ref_name == 'dotnet-vnext'
    uses: ./.github/workflows/rebase.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      base: ${{ github.event.client_payload.ref_name }}
      branch: ${{ github.event.client_payload.ref_name == 'dotnet-vnext' && 'dotnet-nightly' || 'main' }}
      repository: ${{ github.event.client_payload.repository }}
