name: issue-metrics

on:
  schedule:
    - cron: '30 02 1 * *'
  workflow_dispatch:

permissions: {}

jobs:

  metrics:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false

    environment:
      name: admin
      deployment: false

    permissions:
      id-token: write

    steps:

    - name: Get dates for last month
      id: last-month
      shell: bash
      run: |
        first_day=$(date -d "last month" +%Y-%m-01)
        last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)
        echo "$first_day..$last_day"
        echo "last-month=$first_day..$last_day" >> "${GITHUB_OUTPUT}"

    - name: Get GitHub token
      id: get-github-token
      uses: martincostello/github-automation/actions/get-github-token@279f5d3cc244dfdd9bb1197d2ab6996c37cb4486 # get-github-token/v4.3.3
      with:
        profile-name: read

    - name: Run issue-metrics tool
      uses: github-community-projects/issue-metrics@44173f9e0a3b2144a777a10a340e4c09a25ac9f8 # v4.2.8
      env:
        GH_TOKEN: ${{ steps.get-github-token.outputs.token }}
        IGNORE_USERS: 'codecov[bot],Copilot,costellobot,costellobot[bot],dotnet-bumper[bot],dotnet-patch-automation-updater[bot],github-actions[bot],renovate[bot]'
        SEARCH_QUERY: 'owner:${{ github.repository_owner }} created:${{ steps.last-month.outputs.last-month }} -reason:"not planned" -author:app/dependabot'

    - name: Output the report
      shell: bash
      run: cat ./issue_metrics.md >> "${GITHUB_STEP_SUMMARY}"
