name: lint

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  lint:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ 'ubuntu-22.04', 'ubuntu-24.04' ]
    steps:
    - name: Dump CPU information
      run: lscpu
