name: repro

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        filter: 'tree:0'
        show-progress: false

    - name: Run script
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"
        Install-Module -Name powershell-yaml -Force -MaximumVersion '0.4.12'
        ./lint.ps1
