name: update-static-assets

on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:
    inputs:
      repository:
        description: 'An optional single repository to update.'
        required: false
        type: string
        default: ''

permissions: {}

jobs:

  get-repos:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false

    environment:
      name: maintenance
      deployment: false

    outputs:
      repos: ${{ steps.get-repos.outputs.repos }}

    permissions:
      id-token: write

    steps:

      - name: Get GitHub token
        id: get-github-token
        uses: martincostello/github-automation/actions/get-github-token@279f5d3cc244dfdd9bb1197d2ab6996c37cb4486 # get-github-token/v4.3.3
        with:
          profile-name: maintenance

      - name: Get repositories
        id: get-repos
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.get-github-token.outputs.token }}
          REPOSITORY: ${{ github.event.inputs.repository || '' }}
        run: |
          $repo = ${env:REPOSITORY}
          if (-Not [string]::IsNullOrEmpty($repo)) {
            if (-Not $repo.Contains('/')) {
              $repo = "${env:GITHUB_REPOSITORY_OWNER}/${repo}"
            }
            $repos = @($repo)
          } else {
            $contents = gh api "repos/${env:GITHUB_REPOSITORY}/contents/.github/workflow-config.json?ref=${env:GITHUB_SHA}" | ConvertFrom-Json
            $repos = ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($contents.content)) | ConvertFrom-Json).'update-static-assets'
          }

          $filteredRepos = @()
          foreach ($repo in $repos) {
            if ($repo.StartsWith("${env:GITHUB_REPOSITORY_OWNER}/")) {
              $filteredRepos += $repo
            }
          }
          $reposJson = ConvertTo-Json $filteredRepos -Compress
          "repos=${reposJson}" >> ${env:GITHUB_OUTPUT}

  update-static-assets:
    name: 'update-${{ matrix.repo }}'
    needs: get-repos
    runs-on: ubuntu-slim
    timeout-minutes: 10
    if: needs.get-repos.outputs.repos != '[]'

    concurrency:
      group: 'update-assets-${{ matrix.repo }}'
      cancel-in-progress: false

    environment:
      name: maintenance
      deployment: false

    permissions:
      id-token: write

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        repo: ${{ fromJSON(needs.get-repos.outputs.repos) }}

    steps:

    - name: Get GitHub token
      id: get-github-token
      uses: martincostello/github-automation/actions/get-github-token@279f5d3cc244dfdd9bb1197d2ab6996c37cb4486 # get-github-token/v4.3.3
      with:
        profile-name: maintenance

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        filter: 'tree:0'
        persist-credentials: false
        repository: ${{ matrix.repo }}
        show-progress: false
        submodules: recursive
        token: ${{ steps.get-github-token.outputs.token }}

    - name: Update static assets
      uses: martincostello/update-static-assets@f3f8cbbb93561daeb7efc78f736538c6ede2c3e6 # v4.0.2
      with:
        file-extensions: 'cshtml,erb,html,razor'
        labels: dependencies
        repo: ${{ matrix.repo }}
        repo-token: ${{ steps.get-github-token.outputs.token }}
        user-email: ${{ vars.GIT_COMMIT_USER_EMAIL }}
        user-name: ${{ vars.GIT_COMMIT_USER_NAME }}
